language:
  - bash

services:
  - docker

sudo: true

jobs:
  include:
    - stage: build
      script: ./ci/bin/docker_build_and_push.sh 2.12/alpine scala scala:2.12 scala:2.12-alpine scala:2.12-1.2.3 scala:2.12-1.2.3-alpine

