on: [push]

name: build

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@master
      with:
        submodules: true

    - name: Build Docker Images
      run: |
        ./ci/bin/docker_build_and_push.sh 2/alpine scala scala:2 scala:2.13 scala:2.13.1 scala:2.13.1-alpine scala:2.13-1.3.2 scala:2.13.1-1.3.2-alpine
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: ${{ secrets.DOCKER_ORGANIZATION }}
        GITHUB_ORGANIZATION: ${{ secrets.GITHUB_ORGANIZATION }}
