on: [push]

name: build

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
    - name: Build Docker Images
      uses: philips-software/docker-ci-scripts@v1.0.1
      with:
        dockerfile: 2/alpine
        tags: scala scala:2 scala:2.13 scala:2.13.1 scala:2.13.1-alpine scala:2.13-1.3.2 scala:2.13.1-1.3.2-alpine
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
